controller_frequency: 10.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false
shutdown_costmaps: false
controller_patience: 5.0
planner_frequency: 2.0
planner_patience: 5.0
oscillation_timeout: 0.0
oscillation_reset_dist: 0.5
oscillation_distance: 0.1
conservative_reset_dist: 0.10

TrajectoryPlannerROS:
   max_vel_x: 0.3
   min_vel_x: 0.1
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 0.5
   min_vel_theta: -0.5
   min_in_place_vel_theta: 0.5
   escape_vel: -0.1
   acc_lim_x: 2.5
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 3.2

   holonomic_robot: false
   yaw_goal_tolerance: 0.2 # about 6 degrees
   xy_goal_tolerance: 0.3  # 10 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.1
   gdist_scale: 0.2
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.1
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 3.5
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 20
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 40
   dwa: true
simple_attractor: false
